name: Deploy React App to S3 & CloudFront

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build
        # Vite outputs to /dist by default

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Hardcode for now to test

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete --region ${{ secrets.AWS_REGION }}  # Explicit region here too

      - name: Deploy to S3 with correct cache headers
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete \
            --cache-control "public, max-age=60, must-revalidate" \
            --exclude "*" \
            --include "*.html" 

          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude "*.html" \
            --exclude "index.html"

      - name: Invalidate CloudFront (only the changed files)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
            --paths "/static/js/chatbox.js" \
                    "/static/js/chatbox.chunk.js" \
                    "/static/css/chatbot.css" \
                    "/index.html"